language: ruby

rvm:
  - 2.1.2

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database geotappy_api_test' -U postgres

