apns:
  cert:       'prod_cert.pem'
  env:        'prod'
  passphrase: ''

google:
  api_key: ''

logger:
  level:    'info'
  facility: 'LOG_LOCAL1'

sidekiq:
  password: ''

secret_key: ''

token:
  expires_in: 100000


